/// Flutter icons Phantom
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Phantom
///      fonts:
///       - asset: fonts/Phantom.ttf
///
///
///
import 'package:flutter/widgets.dart';

class PhantomIcons {
  PhantomIcons._();

  static const _kFontFam = 'Phantom';
  static const String? _kFontPkg = null;

  static const IconData auto =
      IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monitor =
      IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slave_master =
      IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData master_slave =
      IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData night =
      IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData manual =
      IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fan =
      IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData humidity =
      IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insert =
      IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData evac =
      IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temp_evac =
      IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
